### ISSUE TITLE
Add docker version as advertised.

### ISSUE THREAD

**Issue by fishpm-anu** [bitnami/bitnami-docker-jupyterhub#4]
### Name and Version

bitnami/jupyterhub

### What is the problem this feature will solve?

I see in the jupyterhub repo its only for K8s deployment. Even though the page https://bitnami.com/stack/jupyterhub/containers
states its for both platforms. I see from the other issues that is autogenerated? I think its actually correct and you should provide what's needed for it to run as stated on both platforms.

Many Uni's/orgs (perhaps most Uni's) such as mine don't have the resources to run our own Kubernetes infrastructure OR/AND don't have the money to run k8s as a service in the commercial cloud, but have good bare metal servers and skills in sys admin and basic docker. Many Uni's around the world would benefit if you could provide a docker only version too as per advertised on - https://bitnami.com/stack/jupyterhub/containers

Thanks
Peter 
ANU

### What is the feature you are proposing to solve the problem?

provide a docker compose file and if need be an alternate dockerfile in the repo so it can be run under just docker, using docker-compose on a server.

### What alternatives have you considered?

a more advanced large deployed based on 
https://opendreamkit.org/2018/10/17/jupyterhub-docker/
but a smaller one for a lab of around 10-30 people would be better done based of this repo I feel.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry if it was misleading.
  This asset was intended to be run in a kubernetes environment. This current implementation of the hub container will only talk to a k8s api to launch new containers for the users. I know there are other implementations that allow also to be run in a docker only environment.
  For a bare metal and without getting into all husle of a full k8s deployment, maybe you can go with a small k8s, like minikube or k3s, or you could try the one you linked.

**Comment by fishpm-anu** [comment]
Hi Rafael,
Thanks for the quick reply. From that is it fair to say bitnami is unable or unwilling to produce a docker only version, say like you did with redmine?

**Comment by rafariossaa** [comment]
Hi,
  We are a small team with many duties. Currently that it is not in our road map. 
  In any case, PRs are welcome. We will be glad to review and merge them.

**Comment by fishpm-anu** [comment]
Hi Rafael, I understand.  
Could you then remove the references to docker (especially the  in the README.md file that would be good, so other viewers don't get misled. Like what's the point of the docker commands in the section" Get this image"? Also what's the purpose of the docker compose file in the repo, is that used by kubenetes?
Also you might want to change the section TL;D" to read, "This image can only be run in a Kubernetes cluster". Its clearer, since using "is meant" implies it can also run in docker as is but not a good idea. Especially when one sees a docker-compose file in the repo.

Also the page https://bitnami.com/stack/jupyterhub/containers, you should remove the docker option under containers since its totally misleading/untrue. Unless the azure container works of course, then just remove the dockerhub debian one.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for the suggestions, Would you like to send a PR to change the README ?

**Comment by fishpm-anu** [comment]
Sure, but first can you explain the purpose of this repo to me first? is it used by the kubenetes helm chart?
How do we change this page ? https://bitnami.com/stack/jupyterhub/containers
thanks.

**Comment by rafariossaa** [comment]
Yes, this image is used by [this chart](https://github.com/bitnami/charts/tree/master/bitnami/jupyterhub).

You can not change that page as it is an internal one. As it is automatically generated maybe a note in the README would be a way to workaround this.

**Comment by fishpm-anu** [comment]
Ok I will put in a PR for the changed readme, after Easter
