### ISSUE TITLE
Does this chart supports LDAP authentication for JupyterHub?

### ISSUE THREAD

**Issue by mhthaque** [bitnami/bitnami-docker-jupyterhub#5]
### Name and Version

bitnami/jupyterhub --version 1.1.14

### What is the problem this feature will solve?

I was able to deploy JupyterHub with SSL on our Rancher Kubernetes. But I am trying to find out if this chart (bitnami/jupyterhub --version 1.1.14) supports LDAP auth for syanching AD users and groups? 

### What is the feature you are proposing to solve the problem?

I was able to deploy JupyterHub with SSL on our Rancher Kubernetes. But I am trying to find out if this charts (bitnami/jupyterhub --version 1.1.14) supports LDAP auth for syanching AD users and groups? 

### What alternatives have you considered?

I was able to deploy JupyterHub with SSL on our Rancher Kubernetes. But I am trying to find out if this chart. (bitnami/jupyterhub --version 1.1.14) supports LDAP auth for syanching AD users and groups?

**Comment by rafariossaa** [comment]
Hi,
  I am sorry but this chart doesn't support LDAP.
  Maybe something could be done using `hub.configuration`, but that would depend on how ldap authentication is configured in juypyterhub.
