### ISSUE TITLE
Update ltiauthenticator package included in jupyterhub container image

### ISSUE THREAD

**Issue by rmoreas** [bitnami/bitnami-docker-jupyterhub#6]
### Name and Version

bitnami/jupyterhub:1.5.0

### What is the problem this feature will solve?

The ltiauthenticator package installed in this image is lagging behind. Current installed version is 1.0, while the
latest version is 1.3: https://github.com/jupyterhub/ltiauthenticator.

Version 1.3 is needed to use the LTI 1.3 authenticator and config handler, and to be able to configure "username_key" in the LTI 1.1 Authenticator.

### What is the feature you are proposing to solve the problem?

Include ltiauthenticator 1.3 in the build

**Comment by carrodher** [comment]
Please note we are not installing nor configuring _ltiauthenticator_ but using the version provided by the application itself. If there is a new version, it should be updated when bundled as part of the application itself
